### ISSUE TITLE
Reflection zone plate not properly implemented

### ISSUE THREAD

**Issue by pforson** [hz-b/rayx#161] opened 2023-06-26 08:44 UTC
**Describe the bug**
Tracing a reflection zone plate (single zone plate or multiple) results in a 'correct' trace when the alignment of the zone plate is perfect (World Position: x=0, y=0, z=90). However, if the zone plate is shifted in the x-axis then the resulting trace does not correlate with either real world measured data or ray-ui (see png and rml files posted in mattermost).

**To Reproduce**
1. Trace test_singleRZP_widePointSource_X0.5.rml in ray-x
2. Trace test_singleRZP_widePointSource_X0.5.rml in ray-ui.
3. Compare plots.

Note - in order to make a comparison between ray-ui and ray-x I used the 'alignment error' setting in ray-ui to generate the x-offset in the rml file. This is not 100% correct in relation to experiment data, because the camera does not move in conjunction with the RZP. However, the same incorrect behaviour can be seen when tracing in ray-x using a 'multi-RZP' in which the RZP(s) is in a 'group' with the camera and both are offset.

**Expected behavior**
Ray-x plots should be identical to ray-ui.

**Screenshots**
![RAY_UI_test_singleRZP_widePointSource_X0 5](https://github.com/hz-b/rayx/assets/10009675/bf412821-9224-42a1-adf6-49439550470e)

![RAY-X_test_singleRZP_widePointSource_X0 5](https://github.com/hz-b/rayx/assets/10009675/e4456d21-48b0-4f55-b8c2-1cfdae64932d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by Atraxus** [comment] 2023-11-07 15:15
@pforson, closing this issue. The RZP seems to work as intended for now

**Closed by Atraxus** 2023-11-07 15:15 UTC
Labels: C-bug, A-core-model
